### ISSUE TITLE
Add documentation to show what proper outcome of import should look like

### ISSUE THREAD

**Issue by lnkassa** [battery-lcf/batteryarchive-agent#36]

**Comment by lnkassa** [comment]
What determines admin email and password for redash? I don't remember going through this in the droplet demo and I can't remember how I did it locally.

**Comment by Scarzer** [comment]
The admin email and password are set by the user when going through the `/bin/setup` script. It sets the `DEFAULT_EMAIL` and `ADMIN_PASSWORD` environment variables.
